config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  resources :users
  authenticate :user do
    resources :articles, :path => "blog", only: [:new, :create, :edit, :update, :destroy] do
      resources :comments
    end
  end
  resources :articles, :path => "blog", only: [:show, :index]

  get '/profile', as: 'user_root', to: 'users#profile'
  get '/privacy', to: 'privacy#index'
  root 'welcome#index'

end

app/models/user.rb
# Copyright 2015 Unicode4all
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License. 

class User < ActiveRecord::Base
  has_and_belongs_to_many :roles
  before_create :set_default_role
  

  def role?(role)
    return !!self.roles.find_by_name(role.to_s)
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  validates :name,
    :presence   => true,
    :format     => /[a-zA-Z0-9\s]+/
  
  private
  def set_default_role
    self.roles.push Role.find_by_name('normal')
  end
  
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController  
  
  def new
    if User.where(:id => 1).blank?
      @page_title="Register Admin Account" or "Register"
    end
    super
  end
  
  def create
    @page_title="Register"
    super
  end
  private
  
  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
# Copyright 2015 Unicode4all
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License. 

class UsersController < ApplicationController
  before_filter :get_user, :only => [:index,:new,:edit]
  before_filter :accessible_roles, :only => [:new, :edit, :show, :update, :create]
  load_and_authorize_resource :only => [:show,:new,:destroy,:edit, :update]
  
  # GET /users
  # GET /users.xml                                                
  # GET /users.json                                       HTML and AJAX
  #-----------------------------------------------------------------------
  def index 
    authorize! :manage, @users
    @users = User.accessible_by(current_ability, :index).limit(20)
    respond_to do |format|
      format.json { render :json => @users }
      format.xml  { render :xml => @users }
      format.html
    end
  end
  
  def profile
    if params.has_key?(:user)
      @user = User.find_by_name(params[:user]) or not_found
    else
      @user = current_user
    end
    @page_title = "Profile"
  end
  # GET /users/new
  # GET /users/new.xml                                            
  # GET /users/new.json                                    HTML AND AJAX
  #-------------------------------------------------------------------
  def new
    respond_to do |format|
      format.json { render :json => @user }   
      format.xml  { render :xml => @user }
      format.html
    end
  end
  
  # GET /users/1
  # GET /users/1.xml                                                       
  # GET /users/1.json                                     HTML AND AJAX
  #-------------------------------------------------------------------
  def show
    respond_to do |format|
      format.json { render :json => @user }
      format.xml  { render :xml => @user }
      format.html      
    end
    
  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:json, :xml, :html)
  end
  
  # GET /users/1/edit                                                      
  # GET /users/1/edit.xml                                                      
  # GET /users/1/edit.json                                HTML AND AJAX
  #-------------------------------------------------------------------
  def edit
    respond_to do |format|
      format.json { render :json => @user }   
      format.xml  { render :xml => @user }
      format.html
    end
    
  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:json, :xml, :html)
  end
  
  # DELETE /users/1     
  # DELETE /users/1.xml
  # DELETE /users/1.json                                  HTML AND AJAX
  #-------------------------------------------------------------------
  def destroy
    @user.destroy!
    
    respond_to do |format|
      format.json { respond_to_destroy(:ajax) }
      format.xml  { head :ok }
      format.html { respond_to_destroy(:html) }      
    end
    
  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:json, :xml, :html)
  end
  
  # POST /users
  # POST /users.xml         
  # POST /users.json                                      HTML AND AJAX
  #-----------------------------------------------------------------
  def create
    @user = User.new(params[:user])
    
    if @user.save
      respond_to do |format|
        format.json { render :json => @user.to_json, :status => 200 }
        format.xml  { head :ok }
        format.html { redirect_to :action => :index }
      end
    else
      respond_to do |format|
        format.json { render :text => "Could not create user", :status => :unprocessable_entity } # placeholder
        format.xml  { head :ok }
        format.html { render :action => :new, :status => :unprocessable_entity }
      end
    end
  end
  def accessible_roles
    @accessible_roles = Role.accessible_by(current_ability,:read)
  end
  
  # Make the current user object available to views
  #----------------------------------------
  def get_user
    @current_user = current_user
  end
  
  def update
    if params[:user][:password].blank?
      [:password,:password_confirmation,:current_password].collect{|p| params[:user].delete(p) }
    else
      @user.errors[:base] << "The password you entered is incorrect" unless @user.valid_password?(params[:user][:current_password])
    end
    
    respond_to do |format|
      if @user.errors[:base].empty? and @user.update_attributes(params[:user])
        flash[:notice] = "Your account has been updated"
        format.json { render :json => @user.to_json, :status => 200 }
        format.xml  { head :ok }
        format.html { render :action => :edit }
      else
        format.json { render :text => "Could not update user", :status => :unprocessable_entity } #placeholder
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
        format.html { render :action => :edit, :status => :unprocessable_entity }
      end
    end
    
  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:js, :xml, :html)
  end
end

app/helpers/users_helper.rb
# Copyright 2015 Unicode4all
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License. 

module UsersHelper
end

app/views/users/_user_fields.html.erb
<%#
# Copyright 2015 Unicode4all
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License. 
%>

<p><%= f.label :name %></p>
<p><%= f.text_field :name %></p>

<p><%= f.label :email %></p>
<p><%= f.text_field :email %></p>

<% if can? :read, Role %>
  <p><%= f.label :role %></p>
      <%#<%= habtm_checkboxes(@user, :role_ids, @accessible_roles, :name) %>
<% end %>

app/views/users/edit.html.erb
<%#
# Copyright 2015 Unicode4all
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License. 
%>
<% if can? :manage, User == false %>
  <% @user = @current_user %>
<%  end %>
<h3><%= @user == @current_user ? "Your Account Settings" : "Edit User" %></h3>

<%= form_for(@user, :html => { :method => :put }) do |f| %>
  <%= render :partial => 'user_fields', :locals => { :f => f } %>

  <p><%= f.label :password %> <i>(leave blank if you don't want to change it)</i></p>
  <p><%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %></p>
  <p><%= f.password_field :password_confirmation %></p>

  <p><%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i></p>
  <p><%= f.password_field :current_password %></p>

  <p><%= f.submit "Update", class: "small button" %></p>
<% end %>
<%= link_to "Back", :back %>

app/views/users/index.html.erb
<%#
# Copyright 2015 Unicode4all
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License. 
%>

<table>
    <% @users.each do |u| %>
      <tr>
          <td><%= link_to_if(can?(:read, User), "#{u.name}", user_path(u.id)) {} %></td>
          <td><%= "#{u.email}" %></td>
          <td><%= "#{u.roles.collect{|r| r.name}}" %></td>
          <td><%= link_to_if(can?(:edit, User), "Edit", edit_user_path(u.id)) {} %></td>
          <td>
              <i class="fa fa-trash-o">&nbsp;
              </i><%= link_to_if(can?(:delete, u), "Delete", u, :confirm => "Are you sure?", :method => :delete) {} %></td>

      </tr>
    <% end %>
</table>

app/views/users/new.html.erb
<%#
# Copyright 2015 Unicode4all
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License. 
%>

<h2>Register User</h2>

<%= form_for(@user) do |f| %>>

  <%= render :partial => 'user_fields', :locals => { :f => f } %>

  <p><%= f.label :password %></p>
  <p><%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %></p>
  <p><%= f.password_field :password_confirmation %></p>

  <p><%= f.submit "Register" %></p>
<% end %>

app/views/users/profile.html.erb
<%#
# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
%>

<div class="comment">
    <p>
        <%= link_to "Edit", edit_user_registration_path %><br>
        Nickname: <%=  @user.name %><br>
        Registered: <%= @user.created_at.strftime("%d %B %Y") %>
    </p>
</div>

app/views/users/show.html.erb
<%#
# Copyright 2015 Unicode4all
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License. 
%>

<h3><%= @user.name %></h3>

<%= link_to_if(can?(:update,@user), "Edit", edit_user_path(@user)) %> |
<%= link_to_if(can?(:delete, @user), "Delete", user_path(@user), :confirm => "Are you sure?", :method => :delete) {} %>

<table class="one-column-emphasis">
    <tbody>
        <tr>
            <td class="oce-first">Role:</td>
            <td><%= @user.roles.first.name %></td>
        </tr>
        <% if can?(:see_timestamps,User) %>
          <tr>
              <td class="oce-first">Created at:</td>
              <td><%= @user.created_at %></td>
          </tr>
          <tr>
              <td class="oce-first">Last Sign In:</td>
              <td><%= @user.last_sign_in_at %></td>
          </tr>
          <tr>
              <td class="oce-first">Sign In Count:</td>
              <td><%= @user.sign_in_count %></td>
          </tr>
        <% end %>
    </tbody>
</table>